// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2HUVgsQvlFw6jgW1ou0MM6SbXuGwEg6E',
    appId: '1:24844505947:web:7b44cb34d70a6c0c5cc07e',
    messagingSenderId: '24844505947',
    projectId: 'crudoperationsfirebase-47b8f',
    authDomain: 'crudoperationsfirebase-47b8f.firebaseapp.com',
    storageBucket: 'crudoperationsfirebase-47b8f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcedrLmQgNcrgiaagU8ldCwhkKoUIkKWA',
    appId: '1:24844505947:android:0475f6f7e5d761515cc07e',
    messagingSenderId: '24844505947',
    projectId: 'crudoperationsfirebase-47b8f',
    storageBucket: 'crudoperationsfirebase-47b8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5qFYZai8vAxuJbhkOKmENJkOS5jD8BCo',
    appId: '1:24844505947:ios:b4858b41a9fad1bb5cc07e',
    messagingSenderId: '24844505947',
    projectId: 'crudoperationsfirebase-47b8f',
    storageBucket: 'crudoperationsfirebase-47b8f.appspot.com',
    iosClientId: '24844505947-a9vhln9p8cor4arthacmu1m90qlpbolp.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudFlutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5qFYZai8vAxuJbhkOKmENJkOS5jD8BCo',
    appId: '1:24844505947:ios:9659b295bb9d7efe5cc07e',
    messagingSenderId: '24844505947',
    projectId: 'crudoperationsfirebase-47b8f',
    storageBucket: 'crudoperationsfirebase-47b8f.appspot.com',
    iosClientId: '24844505947-9mtof55ankf0o2gg8331j8u25chb4628.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudFlutterFirebase.RunnerTests',
  );
}
